// <auto-generated />
using System;
using Crm.Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Crm.Infra.Migrations
{
    [DbContext(typeof(ClientContext))]
    partial class ClientContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Crm.ApplicationCore.Entity.Client", b =>
                {
                    b.Property<int>("cliID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("cliAtivo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("cliData")
                        .HasColumnType("datetime2");

                    b.Property<string>("cliEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cliNome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("cliSexo")
                        .HasColumnType("int");

                    b.HasKey("cliID");

                    b.ToTable("Clientes");
                });
#pragma warning restore 612, 618
        }
    }
}
